### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kalan4iki** [kalan4iki/skiog-imu#8]
- [ ] Изображения в front и back.
- [ ] Сообщения по задачам front.
- [ ] Разграничение доступа front и back.
- [ ] Механизм модерации, согласования и исполнения front и back.
